### ISSUE TITLE
`wave fetch` server downloads linux rather darwin in Mac M1

### ISSUE THREAD

**Issue by sairaamv** [h2oai/wave#1210]
Here is my M1 Mac log 

```
sai@mbp21 doc-checker % ./venv/bin/wave fetch
Fetching examples and related files. Please wait...
Downloading https://github.com/h2oai/wave/releases/download/v0.20.0/wave-0.20.0-linux-amd64.tar.gz
Extracting...

All additional files downloaded and extracted successfully!
Examples and tour............. /Users/sai/projects/doc-checker/wave/examples
Demos and layout samples...... /Users/sai/projects/doc-checker/wave/demo
Automated test harness........ /Users/sai/projects/doc-checker/wave/test
Wave daemon for deployments... /Users/sai/projects/doc-checker/wave
```

Please let me know if you need any other log. 

```sai@mbp21 doc-checker % wave run app.run     
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [79290] using statreload
INFO:     Started server process [79307]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpcore/_async/connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpcore/_async/connection.py", line 119, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpcore/_backends/asyncio.py", line 270, in open_tcp_stream
    return SocketStream(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [Errno 61] Connect call failed ('127.0.0.1', 10101)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/h2o_wave/server.py", line 242, in _register
    await self._wave.call(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/h2o_wave/server.py", line 199, in call
    return await self._http.post(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpx/_client.py", line 1633, in post
    return await self.request(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/sai/.pyenv/versions/3.9.10/lib/python3.9/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectError: [Errno 61] Connect call failed ('127.0.0.1', 10101)

ERROR:    Application startup failed. Exiting.
```

**Comment by sairaamv** [comment]
Hi @lo5 , Yes I did holler without deep-diving into wave fetch 🙏🏽  - my bad. 
v0.20 is awesome and with some quick dabble, I do like the `ui.header_card` and wave-cli 💯
