### ISSUE TITLE
Embed default `--web-dir`

### ISSUE THREAD

**Issue by zoido** [h2oai/wave#1232]
#### Is your feature request related to a problem? Please describe

I'm always frustrated when ... 😄
I cannot put `waved` binary somewhere in my `$PATH` and use it from working directory.

```
/MY/PWD $ waved --flags

panic: failed reading default index.html page: open /MY/PWD/www/index.html: no such file or directory

goroutine 1 [running]:
github.com/h2oai/wave.Run(0x8c7518, 0x6, 0x8c7e80, 0xe, 0x84fd2c, 0x6, 0x84f448, 0x1, 0xc000156120, 0x28, ...)
        /home/runner/work/wave/wave/server.go:124 +0x2145
main.main()
        /home/runner/work/wave/wave/cmd/wave/main.go:221 +0x139
```

Sure, I can specify `--web-dir` on each call or create an alias. But in that case I'd need to update the www data with new versions of `waved`.

`0.20.0+` wave includes `waved` with the Python package but more advanced flags are not exposed (e.g. all `--oidc-` flags) so running `waved` separately is necessary for particular cases.

#### Describe the solution you'd like

Embed www data into the binary and load them when the `--www-dir` is not explicitly specified.

**Comment by lo5** [comment]
Thanks for the feedback! Using `go:embed` would make sense here, but we have to put some think-time into front-end extensibility / custom-components before doing that. Our static front-end build today makes it easy to `go:embed`, but we need allowance for an escape-hatch in case we also have to compile in third-party app-specific UI components.

> 0.20.0+ wave includes waved with the Python package but more advanced flags are not exposed (e.g. all --oidc- flags) so running waved separately is necessary for particular cases.

The `wave run` command is intended for development-time use only, so we don't pass on any extra flags to `uvicorn` or `waved`. All the `waved` flags are also exposed as env vars: https://wave.h2o.ai/docs/configuration#environment-variables if you do need to set them during development.
