### ISSUE TITLE
wave 0.22 skip start server to run app occured error

### ISSUE THREAD

**Issue by lx1054331851** [h2oai/wave#1482]
#### windows 10: 19044.1706

![image](https://user-images.githubusercontent.com/12423206/172033187-13d4cf4d-06e2-4ce0-a28d-9cafcd89cebd.png)

In the latest documents, user can skip the first step to start the wave server if you're running Wave 0.20.0 or later.

But if i do not start the server first, and run the command "python hello_world.py", the following error occured:
```
Traceback (most recent call last):
  File "C:\Users\lx105\PycharmProjects\MyPy\H2o Wave\wave self\hello_world.py", line 11, in <module>
    page.save()
  File "C:\Users\lx105\Anaconda3\envs\h2o\lib\site-packages\h2o_wave\core.py", line 567, in save
    self.site._save(self.url, p)
  File "C:\Users\lx105\Anaconda3\envs\h2o\lib\site-packages\h2o_wave\core.py", line 632, in _save
    raise ServiceError(f'Request failed (code={res.status_code}): {res.text}')
h2o_wave.core.ServiceError: Request failed (code=502): 
```

**Comment by mturoci** [comment]
This behavior applies to Wave apps only, not Wave scripts. Good catch @lx1054331851 , will make it more obvious in the docs!

**Comment by lx1054331851** [comment]
I got it. Thanks for your reply.
