### ISSUE TITLE
Grouping in Form tables using groupable=True option gives incorrect grouping

### ISSUE THREAD

**Issue by n-srinidhi** [h2oai/wave#1834]
#### **Wave SDK Version, OS**
0.24.2 Windows 11

#### Actual behavior

I am currently working on a dashboard style Web app, with plot cards and Form Tables. There is a background process that executes every second and updates the components. I have set `groupable=True,` in the table, So as to allow grouping. But when I select a column to group, The rows grouped are random ones, Not related to the selected column. 
This is the displayed table, without any grouping

![image](https://user-images.githubusercontent.com/117831190/218636822-14b423fd-c16c-479f-95d6-b6d477b4359c.png)

After selecting Client column for grouping, 
![image](https://user-images.githubusercontent.com/117831190/218636927-9a222964-8bbe-4cef-9a33-4dc0d81f35c7.png)

![image](https://user-images.githubusercontent.com/117831190/218637050-0bf970ef-2cd8-4bae-a947-9bbecdaeac30.png)

![image](https://user-images.githubusercontent.com/117831190/218637135-62f60c02-83bc-4eb0-b95e-3f21da7c6275.png)

Is it possible that the background process which is updating the Form tables is interfering with the updation?

**Comment by vopani** [comment]
Does the background process update the table data (rows) as well?

**Comment by n-srinidhi** [comment]
Yes it does. Every 2 secs

**Comment by mturoci** [comment]
May be duplicate of https://github.com/h2oai/wave/issues/1687. @n-srinidhi could you please try this out in a [nightly](https://wave.h2o.ai/docs/installation/#early-adopters) build? It could have been fixed in master in the meantime.

**Comment by mturoci** [comment]
@n-srinidhi any updates on the nightly? ^^

**Comment by n-srinidhi** [comment]
@mturoci Hi!Apologies for the late reply!I get the following error while trying to start the wave server with the nightly build installed
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\srini\Desktop\Projects\Centra\centra\Scripts\wave.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'h2o_wave.cli
```
I installed the latest build

**Comment by n-srinidhi** [comment]
I tried installation with [this ](https://github.com/h2oai/wave/releases/download/nightly/h2o_wave-nightly-py3-none-any.whl) as well as [this](https://github.com/h2oai/wave/releases/download/nightly/h2o_wave-nightly-py3-none-win_amd64.whl) file, following the same steps.
1. I uninstalled h2o_wave installed earlier, Installed the nightly build within my virtual environment.
2. Then started the wave server as usual, using `wave run app` command.

**Comment by mturoci** [comment]
https://github.com/h2oai/wave/releases/download/nightly/h2o_wave-nightly-py3-none-win_amd64.whl (win_amd64) is the one to use when you don't want to start wave server separately. Can you try to:

1. Create a new directory and cd into it.
2. Download the whl file linked above and store it in the directory from step 1. 
3. Create a new virtual env - `python -m venv venv`
4. Activate the virtual env - `.\venv\Scripts\activate`
5. Run `pip install downloaded.whl`
6. Run `wave init` and pick hello world template.
7. Run `wave run app`.

I tried these on a Windows machine just now and everything seems to be working. Let's try these first.

**Comment by n-srinidhi** [comment]
Sure Thank you!

**Comment by mturoci** [comment]
@n-srinidhi should be okay now. Please download the whl file again.
