### ISSUE TITLE
Reload Failing with: ERROR:    Application startup failed. Exiting.

### ISSUE THREAD

**Issue by doctrino** [h2oai/wave#1956]
#### Wave SDK Version, OS

`0.25.2` Windows

#### Actual behavior

Running a starter template `wave init` -> `App with header + navigation`

While running app, `wave run app` if I save changes in the `app.py` the application shuts down,
with the message `Error: Application startup failed. Exiting`

<details>
<summary>Full traceback</summary

```bash
WARNING:  StatReload detected changes in 'app.py'. Reloading...
INFO:     Started server process [24748]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\anyio\_core\_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1073, in create_connection
    raise exceptions[0]
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1058, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 964, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\selector_events.py", line 633, in sock_connect
    return await fut
           ^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 10101)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\anyio\_core\_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpcore\_async\connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpcore\backends\auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 109, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\starlette\routing.py", line 654, in startup
    await handler()
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\h2o_wave\server.py", line 297, in _register
    raise exception
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\h2o_wave\server.py", line 281, in _register
    await self._wave.call(
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\h2o_wave\server.py", line 232, in call
    return await self._http.post(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpx\_client.py", line 1845, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-virtual-env-py3.11\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

ERROR:    Application startup failed. Exiting.
````
</details>

#### Expected behavior

Application reloads with new changes

#### Steps To Reproduce

1.  `wave init` -> `App with header + navigation`
2. Start up app `wave run app`
3. Do a change in `app.py` and save.
4. Then, you should see the error above.

**Comment by mturoci** [comment]
Hi @doctrino.

Can you properly visit the app in the browser after the initial `wave run` (without changes)?

> Connect call failed ('127.0.0.1', 10101)

This indicates your Wave server is not reachable or running. Can you verify a `waved` process is running on port 10101? Assuming you did not change the default port.

Another thing that might help isolate the problem is running the app within a regular virtual env instead of `poetry`.

**Comment by doctrino** [comment]
@mturoci Thank you so much for you response. 

I attempted a fresh virtual env environment, no poetry, with the same result. 

I did some reading, and I think it has do with `localhost` vs `127.0.0.1`. On Windows it seems like Docker maps the 127.0.0.1 to some Docker stuff, as I have the following line in my hosts file
> 127.0.0.1 kubernetes.docker.internal

Furthermore, when I start up the app I am told to use `localhost:10101`:

```bash
2023/05/06 18:27:38 # ┌──────────────────────────────────────┐
2023/05/06 18:27:38 # │  Running at http://localhost:10101/  
2023/05/06 18:27:38 # └──────────────────────────────────────┘
```

Shouldn't the reload trigger `h2o-wave` to connect to `localhost:10101` instead of `127.0.0.1:10101`?

**Comment by mturoci** [comment]
> On Windows it seems like Docker maps the 127.0.0.1 to some Docker stuff,

Hold on. Are you running within a docker? If so, a further description of your setup will be needed.

> /etc/hosts 127.0.0.1 kubernetes.docker.internal

IMO, this is the root problem as your Wave app tries to connect to `kubernetes.docker.internal:10101` instead of localhost:10101.

> Shouldn't the reload trigger h2o-wave to connect to localhost:10101 instead of 127.0.0.1:10101

localhost is just an alias for `127.0.0.1` by default. However, since your `127.0.0.1` is mapped to `kubernetes.docker.internal`, you can try setting `H2O_WAVE_ADDRESS=http://localhost:10101` env variable (from the default `http://127.0.0.1:10101`). Assuming there is no localhost mapping in `/etc/hosts`, it could resolve your problem. What do you see when you visit http://localhost:10101 in your browser (after the app crash)?

**Comment by doctrino** [comment]
> Hold on. Are you running within a docker? If so, a further description of your setup will be needed.

No I am not running within docker, but I have docker installed which apparently has captured `127.0.0.1`. 

Yes, I agree that `/etc/hosts 127.0.0.1 kubernetes.docker.internal` the problem. But I wonder if `H20 Wave` can have the flexibility to not require `/etc/hosts 127.0.0.1 localhost`.

I tried running with `H2O_WAVE_ADDRESS=http://localhost:10101`, but the app still crashes upon change, and it seems the application is still trying to connect to `127.0.0.1:10101` as I get the error: `ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 10101)`. When I visit `http://localhost:10101` in the browser after crash I get `This site cannot be reached`, see screenshot below.

<details>
<summary>Traceback</summary>

```
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [13508]
INFO:     Started server process [6400]
INFO:     Waiting for application startup.
ERROR:    anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\anyio\_core\_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1073, in create_connection
    raise exceptions[0]
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1058, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 964, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\selector_events.py", line 633, in sock_connect
    return await fut
           ^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 10101, 0, 0)
----------------------------
Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\anyio\_core\_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1073, in create_connection
    raise exceptions[0]
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1058, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 964, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\selector_events.py", line 633, in sock_connect
    return await fut
           ^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\asyncio\selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 10101)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\anyio\_core\_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpcore\_async\connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpcore\backends\auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 109, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\starlette\routing.py", line 654, in startup
    await handler()
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\h2o_wave\server.py", line 297, in _register
    raise exception
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\h2o_wave\server.py", line 281, in _register
    await self._wave.call(
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\h2o_wave\server.py", line 232, in call
    return await self._http.post(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpx\_client.py", line 1845, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\MyUser\AppData\Local\pypoetry\Cache\virtualenvs\my-env-py3.11\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

ERROR:    Application startup failed. Exiting.
```
</details>


<details>

<summary>Screenshot</summary>

![image](https://github.com/h2oai/wave/assets/60234212/b6b596ea-e86e-424d-aff8-df12c4271864)

</details>

**Comment by mturoci** [comment]
> I wonder if H20 Wave can have the flexibility to not require /etc/hosts 127.0.0.1 localhost

Wave is just a process listening on a specific address + port, from which both are configurable. All the underlying networking goes through OS so there is no way to bypass /etc/hosts. 

My networking knowledge is pretty limited so I might not be able to give you a proper solution, but I would try picking an available private IP address if localhost is already taken up within `/etc/hosts` and go from there. Another alternative would be to remove your localhost => docker mapping, which seems odd.
