### ISSUE TITLE
Docs wrong for dropping all cards

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#2319]
#### Wave SDK Version, OS

<img width="943" alt="image" src="https://github.com/h2oai/wave/assets/4793561/8bcc35ad-8d4c-4e63-a65c-3625df43a47e">

This is not an await function, so docs are wrong

```python
@app("/")
async def serve(q: Q):

    await q.page.drop()

    await q.page.save()  # Update the UI
```

```python
Error
Traceback (most recent call last):
  File "/Users/mtanco/PycharmProjects/att_training/.venv/lib/python3.12/site-packages/h2o_wave/server.py", line 360, in _process
    await self._handle(q)
  File "/Users/mtanco/PycharmProjects/att_training/chat.py", line 22, in serve
    await q.page.drop()
TypeError: object NoneType can't be used in 'await' expression
```
works if you remove await

**Comment by marek-mihok** [comment]
@mtanco, thanks for noticing!
