### ISSUE TITLE
examples.dashboard doesnt work

### ISSUE THREAD

**Issue by shaz13** [h2oai/wave#411]
#### Wave SDK Version, OS

e.g. 0.10.0 20201129141910 , Windows 10, Python 3.8.3 

#### Actual behavior

```
(wave) C:\Users\Shahebaz\Downloads\wave-0.10.0-windows-amd64>wave run examples.dashboard
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [16200] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "e:\anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "e:\anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "e:\anaconda3\lib\site-packages\uvicorn\subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "e:\anaconda3\lib\site-packages\uvicorn\main.py", line 419, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "e:\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "e:\anaconda3\lib\site-packages\uvicorn\main.py", line 426, in serve
    config.load()
  File "e:\anaconda3\lib\site-packages\uvicorn\config.py", line 328, in load
    self.loaded_app = import_from_string(self.app)
  File "e:\anaconda3\lib\site-packages\uvicorn\importer.py", line 23, in import_from_string
    raise exc from None
  File "e:\anaconda3\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "e:\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\examples\dashboard.py", line 7, in <module>
    from synth import FakePercent, FakeCategoricalSeries
ModuleNotFoundError: No module named 'synth'
INFO:     Stopping reloader process [16200]
```
#### Expected behaviour

Dashboard example should work on Windows

#### Steps To Reproduce

1. Start `./waved.exe`
2. Activate the virtual environment
3. Run from the root - `wave run examples.dashboard`

**Comment by mturoci** [comment]
Thanks for the issue @shaz13!

This is not a platform related issue. All the examples currently use our `Faker` module to mock data. This will be changed however in near future thanks to #31. As a quick workaround for now try changing 
```py
from synth import FakePercent, FakeCategoricalSeries
```
to
```py
from .synth import FakePercent, FakeCategoricalSeries
```

Please let me know if that worked for you.

**Comment by shaz13** [comment]
@mturoci - Yeah, works like a charm. Thanks!
