### ISSUE TITLE
Error examples.tour in h2o Wave

### ISSUE THREAD

**Issue by sergiomora03** [h2oai/wave#432]
#### Wave SDK Version, OS

I´have v0.10.0 Wave, windows:

[wave-0.10.0-windows-amd64.tar.gz](https://github.com/h2oai/wave/releases/tag/v0.10.0)

#### Actual behavior

I run `wave run --no-reload examples.tour` from [wave/docs/tour](https://h2oai.github.io/wave/docs/tour) and get this error:

```
Error

Traceback (most recent call last):
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\server.py", line 265, in _process
    await self._handle(q)
  File ".\examples\tour.py", line 193, in serve
    await show_example(q, catalog[route])
  File ".\examples\tour.py", line 162, in show_example
    await active_example.start()
  File ".\examples\tour.py", line 43, in start
    self.process = await asyncio.create_subprocess_exec(
  File "c:\users\samora\anaconda3\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "c:\users\samora\anaconda3\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "c:\users\samora\anaconda3\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```

from [http://localhost:10101/tour](http://localhost:10101/tour) page.

#### Expected behavior

At least interact with:

![image](https://user-images.githubusercontent.com/48146957/102823393-cb576080-43a8-11eb-9ece-09a2fa3dfbfa.png)

#### Steps To Reproduce

1. Download [wave-0.10.0-windows-amd64.tar.gz](https://github.com/h2oai/wave/releases/download/v0.10.0/wave-0.10.0-windows-amd64.tar.gz)
2. Excecute `waved.exe`
3. run `pip install -r examples/requirements.txt`
4. run `wave run --no-reload examples.tour`
5. Go to [http://localhost:10101/tour](http://localhost:10101/tour)
6. Get the error.

**Comment by lo5** [comment]
@sergiomora03 Thanks for reporting!

Duplicates #397

**Comment by sugatoray** [comment]
Same. Problem. Tried twice now. Exactly same error on Windows 10 (Version 2004, Build 19041.X).

**Comment by lo5** [comment]
Thanks for your patience - there's a workaround posted here until we get the next release out: https://github.com/h2oai/wave/issues/397#issuecomment-749750301

**Comment by sergiomora03** [comment]
For me do not work. 
Now, I get this error:

```
Traceback (most recent call last):
  File "C:\Users\samora\OneDrive - Politécnico Grancolombiano\Poli\1 - Proyects\7. CRM\temp\wave\examples\hello_world.py", line 5, in <module>
    from h2o_wave import site, ui
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\__init__.py", line 18, in <module>
    from .core import Site, AsyncSite, site, Page, Ref, data, pack, Expando, expando_to_dict, clone_expando, copy_expando
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\core.py", line 9, in <module>
    import httpx
  File "c:\users\samora\anaconda3\lib\site-packages\httpx\__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "c:\users\samora\anaconda3\lib\site-packages\httpx\_api.py", line 3, in <module>
    from ._client import Client, StreamContextManager
  File "c:\users\samora\anaconda3\lib\site-packages\httpx\_client.py", line 7, in <module>
    import httpcore
  File "c:\users\samora\anaconda3\lib\site-packages\httpcore\__init__.py", line 2, in <module>
    from ._async.connection_pool import AsyncConnectionPool
  File "c:\users\samora\anaconda3\lib\site-packages\httpcore\_async\connection_pool.py", line 2, in <module>
    from ssl import SSLContext
  File "c:\users\samora\anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed while importing _ssl: No se puede encontrar el módulo especificado.
```
Maybe I made a mistake copying the code?

**Comment by gonfernandez** [comment]
Same issue as @sergiomora03 here.

**Comment by lo5** [comment]
Looks like the second error is related to Conda/Pycharm installation/configuration: https://www.google.com/search?q=ImportError%3A+DLL+load+failed+while+importing+_ssl, unrelated to the h2o-wave module.

**Comment by anthony-demaio** [comment]
I'm experiencing the same issue with wave-0.12.1 on Windows. I tried the workaround, and replaced the tour.py file with the one linked, and it did not resolve the issue.

When I go to localhost:10101/tour as instructed in the documentation, I get 404 page not found error.

**Comment by lo5** [comment]
@anthony-demaio That sounds like a different problem.There are two separate problems reported in this issue: `NotImplementedError` and `ImportError: DLL load failed while importing _ssl`. 

You reported "404 page not found", which does not look like it originated from `waved` (`waved` does not display 404 for any URL). Are you sure the `waved` daemon is running?
