### ISSUE TITLE
h2o wave ModuleNotFoundError: No module named 'synth'

### ISSUE THREAD

**Issue by sergiomora03** [h2oai/wave#454]
#### Wave SDK Version, OS

I´have v0.10.0 Wave, windows: [wave-0.10.0-windows-amd64.tar.gz](https://github.com/h2oai/wave/releases/tag/v0.10.0)

#### Actual behavior

When run example documentation code to build plot, I get this error:
```
INFO:     Started server process [6324]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  Detected file change in 'tester_app.py'. Reloading...
ERROR:    Error loading ASGI app. Attribute "main" not found in module "tester_app".
WARNING:  Detected file change in 'tester_app.py'. Reloading...
Process SpawnProcess-4:
Traceback (most recent call last):
  File "c:\users\samora\anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\users\samora\anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\main.py", line 419, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\samora\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\main.py", line 426, in serve
    config.load()
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\config.py", line 328, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\importer.py", line 23, in import_from_string
    raise exc from None
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\users\samora\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\tester_app.py", line 75, in <module>
    from synth import FakeTimeSeries
ModuleNotFoundError: No module named 'synth'
```

#### Expected behavior

At least view th example in documentations of line plot.

#### Steps To Reproduce

Copy this code from [examples/plot-line](https://h2oai.github.io/wave/docs/examples/plot-line) in `tester_app.py` file:

```python
from synth import FakeTimeSeries
from h2o_wave import site, data, ui

page = site['/demo']

n = 50
f = FakeTimeSeries()
v = page.add('example', ui.plot_card(
    box='1 1 4 5',
    title='Line',
    data=data('date price', n),
    plot=ui.plot([ui.mark(type='line', x_scale='time', x='=date', y='=price', y_min=0)])
))
v.data = [(t, x) for t, x, dx in [f.next() for _ in range(n)]]

page.save()
```

Then, run *waved.exe* to build the terminal and the app with `wave run tester_app.py`

End with this error:

```
INFO:     Started server process [6324]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  Detected file change in 'tester_app.py'. Reloading...
ERROR:    Error loading ASGI app. Attribute "main" not found in module "tester_app".
WARNING:  Detected file change in 'tester_app.py'. Reloading...
Process SpawnProcess-4:
Traceback (most recent call last):
  File "c:\users\samora\anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\users\samora\anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\main.py", line 419, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\samora\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\main.py", line 426, in serve
    config.load()
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\config.py", line 328, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\importer.py", line 23, in import_from_string
    raise exc from None
  File "c:\users\samora\anaconda3\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\users\samora\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\tester_app.py", line 75, in <module>
    from synth import FakeTimeSeries
ModuleNotFoundError: No module named 'synth'
```

**Comment by mtanco** [comment]
Hi @sergiomora03, the _synth_ module is in the _examples/synth.py_ file. Is your tester_app.py file in the examples folder as well? If not that would account for the error and you could resolve this either by running your app from that folder or moving Synth to the directory you are working in. 

Issue #31 will change to using hard-coded examples instead of the custom synth data.

**Comment by sergiomora03** [comment]
Excelent, you´re right. Now it´s works.
