### ISSUE TITLE
Server exception thrown when a button is inside ui.expander

### ISSUE THREAD

**Issue by dott1718** [h2oai/wave#510]
#### Wave SDK Version, OS

wave 0.10.0, Ubuntu 18.04 (docker container)

#### Actual behavior

If a button is placed inside ui.expander, the server throws an exception when the button is clicked.

The Exception looks like this
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/dott/Projects/q-model-validation/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dott/Projects/q-model-validation/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/dott/Projects/q-model-validation/venv/lib/python3.8/site-packages/h2o_wave/server.py", line 323, in __call__
    await self._app.app(scope, receive, send)
  File "/home/dott/Projects/q-model-validation/venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/dott/Projects/q-model-validation/venv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/dott/Projects/q-model-validation/venv/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/home/dott/Projects/q-model-validation/venv/lib/python3.8/site-packages/starlette/responses.py", line 152, in __call__
    await self.background()
  File "/home/dott/Projects/q-model-validation/venv/lib/python3.8/site-packages/starlette/background.py", line 18, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/dott/Projects/q-model-validation/venv/lib/python3.8/site-packages/h2o_wave/server.py", line 248, in _process
    events_state = {k: Expando(v) for k, v in events_state.items()}
AttributeError: 'bool' object has no attribute 'items'
```

#### Steps To Reproduce

The following code is sufficient to reproduce the error.

```py
@app('/')
async def serve(q: Q):
    q.page['page'] = ui.form_card(box='3 5 7 5', items=[
        ui.button(name='a1', label='Activate'),
        ui.expander(name='', label='Temp', items=[ui.button(name='a2', label='Activate2')])
    ])
    await q.page.save()
```

The exception is thrown when 'Activate2' button is clicked.

**Comment by lo5** [comment]
@dott1718 Thanks for reporting. The failure is caused because the expander's name is empty. The name is a required parameter per the API. 

We'll add stricter validation for this (via #513), but for now you can 'fix' this by giving the expander a name.
