### ISSUE TITLE
ValueError: Out of range float values are not JSON compliant in h2o wave ui.table

### ISSUE THREAD

**Issue by sergiomora03** [h2oai/wave#570]
#### Wave SDK Version, OS

h2o-wave==0.110

#### Actual behavior

It's retorn me:

```
Unhandled exception
Traceback (most recent call last):
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\server.py", line 281, in _process
    await self._handle(q)
  File ".\app.py", line 20, in serve
    await show_list_dashboard(q)
  File ".\saru\dashboard_list.py", line 172, in show_list_dashboard
    await q.page.save()
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\core.py", line 594, in save
    p = self._diff()
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\core.py", line 499, in _diff
    d = marshal(dict(d=self._changes))
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\core.py", line 794, in marshal
    return json.dumps(d, allow_nan=False, separators=(',', ':'))
  File "c:\users\samora\anaconda3\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\samora\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\samora\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
Failed transmitting unhandled exception
Traceback (most recent call last):
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\server.py", line 281, in _process
    await self._handle(q)
  File ".\app.py", line 20, in serve
    await show_list_dashboard(q)
  File ".\saru\dashboard_list.py", line 172, in show_list_dashboard
    await q.page.save()
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\core.py", line 594, in save
    p = self._diff()
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\core.py", line 499, in _diff
    d = marshal(dict(d=self._changes))
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\core.py", line 794, in marshal
    return json.dumps(d, allow_nan=False, separators=(',', ':'))
  File "c:\users\samora\anaconda3\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\samora\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\samora\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\server.py", line 293, in _process
    await q.page.save()
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\core.py", line 594, in save
    p = self._diff()
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\core.py", line 499, in _diff
    d = marshal(dict(d=self._changes))
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\core.py", line 794, in marshal
    return json.dumps(d, allow_nan=False, separators=(',', ':'))
  File "c:\users\samora\anaconda3\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\samora\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\samora\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```

#### Expected behavior

return table

#### Steps To Reproduce

```python
_id = 0
class issuesDay:
    def __init__(self, case_number: str, title: str, details:str,diff_time: int, priority: float):
        global _id
        _id += 1
        self.id = f'I{_id}'
        self.case_number = case_number
        self.title = title
        self.details=details
        self.diff_time = diff_time
        self.priority=priority

    q.page['casos'] = ui.form_card(box='top', items=[
        ui.table(
            name='issues',
            columns=[
                ui.table_column(name='case_number', label='Número',searchable=True),
                ui.table_column(name='title', label='Título',searchable=True,filterable=True),
                ui.table_column(name='details', label='Tipificación',searchable=True,filterable=True),
                ui.table_column(name='priority', label='Prioridad',cell_type=ui.progress_table_cell_type()),
                ui.table_column(name='diff_time', label='Días',sortable=True, searchable=True,filterable=True),
            ],
            rows=[ui.table_row(
                name=issue.id,
                cells=[str(issue.case_number), str(issue.title), str(issue.details), issue.priority, str(issue.diff_time)]) for
                issue in [
                    issuesDay(
                        case_number=issues.iloc[case]['TicketNumber'],
                        title=issues.iloc[case]['Title'],
                        details=issues.iloc[case]['ilu_typificationdetailName'],
                        priority=issues.iloc[case]['Time']/issues['Time'].max(),
                        diff_time=issues.iloc[case]['Time']
                    ) for case in range(issues.shape[0])
                ]
            ],
            groupable=True,
            downloadable=True,
            resettable=True,
        )
    ])
```

**Comment by mturoci** [comment]
Hi @sergiomora03, this seems like a problem with the data you pass into table. Please have a look at #447 for a possible easy quick fix, otherwise you would have to clean your data yourself until we provide an automatic way to do this.
