### ISSUE TITLE
Error in deserializing FormCard type using `load`

### ISSUE THREAD

**Issue by pramitchoudhary** [h2oai/wave#607]
Tested on versions: `0.12.1` and `0.13.0`, works fine on `0.11.0`

Running into deserialization on using `FormCard.load(...)`. 
Seems like, the error occurs when trying to deserialize `FormCard.items` which are serialized as a `list of dictionaries` into `Component`
 
```
Error
Traceback (most recent call last):
  File "/home/pramit/testing/q/apps/system/auto-insights/venv/lib/python3.7/site-packages/h2o_wave/server.py", line 278, in _process
    await self._handle(q)
  File "./.../ui/main.py", line 1591, in serve
    await handle_route(q)
  File "./.../ui/main.py", line 1527, in handle_route
    populate_previous_state(q)
  File "./.../ui/main.py", line 670, in populate_previous_state
    setattr(q.client, "insight_results", InsightResultsDoc.load(res[0]["data"]).res)
  File "./.../ui/doctypes.py", line 107, in load
    output[insight_type][card_id] = klass.load(card_data)
  File ".../venv/lib/python3.7/site-packages/h2o_wave/types.py", line 5754, in load
    _guard_vector('FormCard.items', __d_items, (Component,), False, False, True)
  File ".../venv/lib/python3.7/site-packages/h2o_wave/types.py", line 48, in _guard_vector
    _guard_scalar(f'{name} element', value, types, False, non_empty, False)
  File ".../venv/lib/python3.7/site-packages/h2o_wave/types.py", line 37, in _guard_scalar
    raise ValueError(f'{name}: want one of {types}, got {type(value)}')
ValueError: FormCard.items element: want one of (<class 'h2o_wave.types.Component'>,), got <class 'dict'>
```
https://github.com/h2oai/wave/blob/a543d41df837e9ba431653d8ea59cc9709287f72/py/h2o_wave/types.py#L5754

**Comment by lo5** [comment]
@pramitchoudhary - we can cut a 0.14 patch release if you want - let me know.
