### ISSUE TITLE
Wave 0.14 running app issue

### ISSUE THREAD

**Issue by psinger** [h2oai/wave#782]
Since switching from 0.13 to 0.14 I receive the following error when running my app:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/psinger/anaconda3/envs/xxx/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/psinger/anaconda3/envs/xxx/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/psinger/anaconda3/envs/xxx/lib/python3.8/site-packages/h2o_wave/server.py", line 395, in __call__
    await self._app.app(scope, receive, send)
  File "/home/psinger/anaconda3/envs/xxx/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/psinger/anaconda3/envs/xxx/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/psinger/anaconda3/envs/xxx/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/home/psinger/anaconda3/envs/xxx/lib/python3.8/site-packages/starlette/responses.py", line 152, in __call__
    await self.background()
  File "/home/psinger/anaconda3/envs/xxx/lib/python3.8/site-packages/starlette/background.py", line 18, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/psinger/anaconda3/envs/xxx/lib/python3.8/site-packages/h2o_wave/server.py", line 254, in _process
    username, subject, client_id, access_token, refresh_token, args = _parse_query(query)
  File "/home/psinger/anaconda3/envs/xxx/lib/python3.8/site-packages/h2o_wave/server.py", line 371, in _parse_query
    head, body = query.split('\n\n', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```

With 0.13 everything works fine. Any idea?

**Comment by AlexWennerDT** [comment]
I too got the same idea after pulling down the recent update! 
![image](https://user-images.githubusercontent.com/78372056/117012020-1ae15d80-acb4-11eb-8cfd-45cd2bf59c24.png)

**Comment by lo5** [comment]
The failing line does not exist in 0.14: https://github.com/h2oai/wave/commit/2958508fbd8680cf21e095e8d63584b1eec8943a#diff-5669ff6fdf94b7bae240e5e24072a0bb986ff137330189eb0ca8fefd00f0c1c0L359

Looks like your Wave server is at 0.14, but the `h2o-wave` Python package in your env is at 0.13? 

`pip install -U h2o-wave` should fix your env.
